title: The Road So Far
email: jlopezcur@gmail.com

path: "https://jlopezcur.github.io"

github_username:  jlopezcur
deviantart_username:  jlopezcur

markdown: kramdown

collections:
    works:
        output: true
        permalink: /:categories/:year/:month/:day/:title.html
        client: "Client"
        type: "image"

gems:
  - jekyll-gist
  - jekyll-seo-tag
